# --- STYLE SYSTEM ---
C_BG = "bg-slate-50 min-h-screen text-slate-900"
C_CONTAINER = "w-full max-w-7xl mx-auto px-6 py-8 gap-6"
C_CARD = "bg-white/90 border border-slate-200/70 rounded-2xl shadow-[0_8px_24px_rgba(15,23,42,0.08)] backdrop-blur transition-all"
C_CARD_HOVER = "hover:border-slate-300 hover:shadow-[0_12px_32px_rgba(15,23,42,0.12)] hover:-translate-y-0.5"
C_BTN_PRIM = "!bg-slate-900 !text-white hover:bg-slate-800 active:scale-[0.98] rounded-lg px-4 py-2 text-sm font-semibold shadow-sm transition-all focus-visible:ring-2 focus-visible:ring-slate-900/30"
C_BTN_SEC = "!bg-white !text-slate-900 border border-slate-200 hover:border-slate-300 hover:bg-slate-50 active:scale-[0.98] rounded-lg px-4 py-2 text-sm font-semibold shadow-sm transition-all focus-visible:ring-2 focus-visible:ring-slate-900/20"
C_INPUT = "border-slate-200/70 bg-white rounded-lg text-sm px-3 py-2 outline-none focus-visible:ring-2 focus-visible:ring-slate-900/20 focus-visible:border-slate-900 w-full transition-all shadow-sm"
C_BADGE_GREEN = "bg-emerald-50 text-emerald-700 border border-emerald-100 px-2 py-0.5 rounded-full text-xs font-medium text-center"
C_BADGE_BLUE = "bg-blue-50 text-blue-700 border border-blue-100 px-2 py-0.5 rounded-full text-xs font-medium text-center"
C_BADGE_GRAY = "bg-slate-100 text-slate-600 border border-slate-200 px-2 py-0.5 rounded-full text-xs font-medium text-center"

C_HEADER = "bg-white/80 border-b border-slate-200/80 h-16 px-6 flex items-center justify-between sticky top-0 z-50 backdrop-blur"
C_BRAND_BADGE = "bg-slate-900 text-white p-2 rounded-lg shadow-sm"
C_NAV_ITEM = "flat text-slate-500 hover:text-slate-900 hover:bg-slate-100/70 px-3 py-1.5 rounded-md transition-all duration-200 no-shadow border-0"
C_NAV_ITEM_ACTIVE = "flat bg-slate-900/5 text-slate-900 px-3 py-1.5 rounded-md transition-all duration-200 no-shadow border-0"
C_PAGE_TITLE = "text-2xl font-semibold text-slate-900 tracking-tight"
C_SECTION_TITLE = "text-sm font-semibold text-slate-600"
C_TABLE_HEADER = "w-full bg-slate-50 border-b border-slate-200 p-4 gap-4"
C_TABLE_ROW = "w-full p-4 border-b border-slate-50 items-center gap-4 hover:bg-slate-50 transition-colors"
