/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppInvitesRouteImport } from './routes/_app.invites'
import { Route as AppExportsRouteImport } from './routes/_app.exports'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppSettingsTaxBankingRouteImport } from './routes/_app.settings.tax-banking'
import { Route as AppSettingsShareRouteImport } from './routes/_app.settings.share'
import { Route as AppSettingsInvoiceNumbersRouteImport } from './routes/_app.settings.invoice-numbers'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppInvoicesNewRouteImport } from './routes/_app.invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitesRoute = AppInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTaxBankingRoute = AppSettingsTaxBankingRouteImport.update({
  id: '/tax-banking',
  path: '/tax-banking',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShareRoute = AppSettingsShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsInvoiceNumbersRoute =
  AppSettingsInvoiceNumbersRouteImport.update({
    id: '/invoice-numbers',
    path: '/invoice-numbers',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/documents': typeof AppDocumentsRoute
  '/expenses': typeof AppExpensesRoute
  '/exports': typeof AppExportsRoute
  '/invites': typeof AppInvitesRoute
  '/ledger': typeof AppLedgerRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/customers/$id': typeof AppCustomersIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/invoice-numbers': typeof AppSettingsInvoiceNumbersRoute
  '/settings/share': typeof AppSettingsShareRoute
  '/settings/tax-banking': typeof AppSettingsTaxBankingRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/documents': typeof AppDocumentsRoute
  '/expenses': typeof AppExpensesRoute
  '/exports': typeof AppExportsRoute
  '/invites': typeof AppInvitesRoute
  '/ledger': typeof AppLedgerRoute
  '/': typeof AppIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/invoice-numbers': typeof AppSettingsInvoiceNumbersRoute
  '/settings/share': typeof AppSettingsShareRoute
  '/settings/tax-banking': typeof AppSettingsTaxBankingRoute
  '/customers': typeof AppCustomersIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/invites': typeof AppInvitesRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/invoice-numbers': typeof AppSettingsInvoiceNumbersRoute
  '/_app/settings/share': typeof AppSettingsShareRoute
  '/_app/settings/tax-banking': typeof AppSettingsTaxBankingRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/documents'
    | '/expenses'
    | '/exports'
    | '/invites'
    | '/ledger'
    | '/settings'
    | '/customers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/account'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/invoice-numbers'
    | '/settings/share'
    | '/settings/tax-banking'
    | '/customers/'
    | '/invoices/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/documents'
    | '/expenses'
    | '/exports'
    | '/invites'
    | '/ledger'
    | '/'
    | '/customers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/account'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/invoice-numbers'
    | '/settings/share'
    | '/settings/tax-banking'
    | '/customers'
    | '/invoices'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/documents'
    | '/_app/expenses'
    | '/_app/exports'
    | '/_app/invites'
    | '/_app/ledger'
    | '/_app/settings'
    | '/_app/'
    | '/_app/customers/$id'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/_app/settings/account'
    | '/_app/settings/company'
    | '/_app/settings/integrations'
    | '/_app/settings/invoice-numbers'
    | '/_app/settings/share'
    | '/_app/settings/tax-banking'
    | '/_app/customers/'
    | '/_app/invoices/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invites': {
      id: '/_app/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AppInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tax-banking': {
      id: '/_app/settings/tax-banking'
      path: '/tax-banking'
      fullPath: '/settings/tax-banking'
      preLoaderRoute: typeof AppSettingsTaxBankingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/share': {
      id: '/_app/settings/share'
      path: '/share'
      fullPath: '/settings/share'
      preLoaderRoute: typeof AppSettingsShareRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/invoice-numbers': {
      id: '/_app/settings/invoice-numbers'
      path: '/invoice-numbers'
      fullPath: '/settings/invoice-numbers'
      preLoaderRoute: typeof AppSettingsInvoiceNumbersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsInvoiceNumbersRoute: typeof AppSettingsInvoiceNumbersRoute
  AppSettingsShareRoute: typeof AppSettingsShareRoute
  AppSettingsTaxBankingRoute: typeof AppSettingsTaxBankingRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsInvoiceNumbersRoute: AppSettingsInvoiceNumbersRoute,
  AppSettingsShareRoute: AppSettingsShareRoute,
  AppSettingsTaxBankingRoute: AppSettingsTaxBankingRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppExportsRoute: typeof AppExportsRoute
  AppInvitesRoute: typeof AppInvitesRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppExportsRoute: AppExportsRoute,
  AppInvitesRoute: AppInvitesRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
